/*

 SIMPLEBACKGROUNDMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 54
   Tile set      : C:\users\hyperion\My Documents\gb_projects\_interstellar\simple_background.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define spacemapWidth 20
#define spacemapHeight 54
#define spacemapBank 0

extern unsigned char spacemap[];

/* End of SIMPLEBACKGROUNDMAP.H */
