/*

 PLANETMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 20
   Tile set      : Z:\home\hyperion\Downloads\gbtd\gbr data\MapTiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define PlanetMapWidth 20
#define PlanetMapHeight 20
#define PlanetMapBank 0

extern unsigned char PlanetMap[];

/* End of PLANETMAP.H */
